
export const FETCH_WEATHER_SUCCESS = 'RECEIVE_WEATHER';
export const GET_TIME = 'GET_TIME';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';
export const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN';
export const GET_INITIAL_STATE = 'GET_INITIAL_STATE'
